FROM node:20-alpine
WORKDIR /app

# Install pnpm
RUN npm install -g pnpm

# Install deps (dev) so watch mode works
COPY package*.json pnpm-lock.yaml* ./
RUN pnpm install

# Copy source
COPY . .

EXPOSE 3000
CMD ["pnpm", "run", "start:dev"]
